services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ddbj-record-specifications
    container_name: ddbj-record-specifications
    volumes:
      - .:/app
    working_dir: /app
    command: ["sleep", "infinity"]
    init: true
