name: Dump JSON Schema

on:
  push:
    branches: [main]
    paths:
      - "ddbj_record/schema/**"
  workflow_dispatch: {}

jobs:
  dump-schema:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install package
        run: uv sync

      - name: Dump schema
        run: |
          uv run dump_json_schema --version v1
          uv run dump_json_schema --version v2

      - name: Commit and push if schema changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet ./schemas; then
            git add ./schemas
            git commit -m "Update JSON Schema files"
            git push origin main
          else
            echo "No changes in schema files, skipping commit."
          fi
